Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('accounts.urls'),),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from . import views 

urlpatterns = [
    url(r'^home/$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login_user, name='login_user'),
    url(r'^logout/$',views.logout_user, name='logout_user'),
]

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)

class MyUserManager(BaseUserManager):
    use_in_migrations = True
    def create_user(self,email,first_name,last_name,password=None):
        if not email:
            raise ValueError('Users must have an email address')
            first_name = first_name,
            last_name = last_name,
        user = self.model(
            email = self.normalize_email(email)
            )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self,email,first_name,last_name,password):
        user = self.create_user(email,first_name,last_name,password = password)
        user.staff = True
        user.save(using=self._db)
        return user

    def create_superuser(self,email,first_name,last_name,password):
        user = self.create_user(email,first_name,last_name,password = password)#,first_name,last_name
        user.staff = True
        user.admin = True
        user.save(using=self._db)
        return user

class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name = 'Email address',
        max_length = 255,
        unique = True
        )
    first_name = models.CharField(max_length = 100)
    last_name = models.CharField(max_length = 100)
    active = models.BooleanField(default = True)
    staff = models.BooleanField(default = False)
    admin = models.BooleanField(default = False)
    objects = MyUserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name','last_name']#'first_name','last_name'

    def get_full_name(self):
        return self.first_name+' '+self.last_name

    def get_short_name(self):
        return self.first_name

    def __str__(self):
        return self.email

    def has_perm(self,perm,obj=None):
        return True

    def has_module_perms(self,app_label):
        return True

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_active(self):
        return self.active



accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from .models import MyUser
class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(label='Password',widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password',widget=forms.PasswordInput)

    class Meta:
        model = MyUser
        fields = ('email','first_name','last_name')#'first_name','last_name'

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = MyUser.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("Email is taken")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self,commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        if commit:
            user.save()
        return user

class UserAdminCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password',widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password',widget=forms.PasswordInput)

    class Meta:
        model = MyUser
        fields = ('email','first_name','last_name')#'first_name','last_name'

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = MyUser.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("Email is taken")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self,commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserAdminChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()
    class Meta:
        model = MyUser
        fields = ('email','password','active','admin','staff')

    def clean_password(self):
        return self.initial["password"]


accounts/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.decorators import login_required
from .models import MyUser
from .forms import RegisterForm
from django.http import *
from django.shortcuts import render_to_response
from django.template import RequestContext

def index(request):
    return render(request,'accounts/home.html')

def login_user(request):
    logout(request)
    context = RequestContext(request)
    email = password = ''
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(email=email,password=password)
        if user is not None:
            print (user.get_full_name())
            login(request,user)
            return redirect('shop:product_list')
        else:
            print("hi")
            messages.error(request,"Invalid Username or Wrong password")
            return render(request,'accounts/login.html')
    else:
        return render(request,'accounts/login.html')

#@login_required(login_url='/login/')

def logout_user(request):
    logout(request)
    return redirect('shop:product_list')

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            if form.clean_email():
                if form.clean_password2():
                    user = form.save()
                    raw_password = form.cleaned_data.get('password1')
                    user = authenticate(email=user.email, password=raw_password)
                    login(request, user)
                    return redirect('shop:product_list')
                else:
                    messages.error(request,"Passwords don't match")
                    redirect ('/account/register/')
            else:
                messages.error(request,"Email is taken")
                redirect('/account/register/')
        else:
            messages.error(request, "There is error in form")
            redirect('/account/register/')
    else:
        form = RegisterForm()
        return render(request,'accounts/register.html',{'form': form})

accounts/templates/accounts/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/css1.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

accounts/templates/accounts/home.html
{% extends 'accounts/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<p>Welcome, {{ user.get_full_name }}.</p>
{% else %}
<p>Welcome, Home.</p>
{% endif %}
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div id="login-block">
    <div id="login">
        <!--<h2 class="text-center text-white pt-5">Login</h2>-->
        <div class="continer">
            <div id="login-row" class="row  align-items-center">
                <div id="login-column">
                    <div id="login-box" >
                        <form id="login-form" class="container" name="LoginForm" action="#" method="post">
                            {% csrf_token %}
                            <h3 class="text-center text-info">Login</h3>
	                        <div class="form-group">
                                <label class="text-info" for="email">Email:</label><br>
                                <input type="text" id="email" name="email" class="form-control" required>
                            </div>
                            <div class="control-group">
                                <label class="text-info" for="password">Password:</label><br>
                                <input type="password" name="password" id="password" class="form-control" required>
                            </div>
                            <div id="reigister-link" class="text-right">
                                <a class="text-info" href="/account/register/">Register here?</a><br>
                            </div>
                            <div class="from-group">
                                <input type="submit" class="btn btn-info btn-md" value="Login">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% block title %} Register {% endblock %}
{% block content %}
{% for message in messages %}
<div class="alert alert-success">
    <a class="close" href="#" data-dismiss="alert">×</a>
    {{ message }}
</div>
{% endfor %}
   <div id="login-block">
       <div id="register-box">
           <form id="register-form" class="container" name="RegisterForm" action="#" method="post">
               {% csrf_token %}
               <h3 class="text-center text-info">Register</h3>
                <div class="form-group">
                    <label class="text-info" for="id_email">Email address:</label><br>
                    <input class="form-control" type="email" id="id_email" name="email"  maxlength="255" required>
                </div>
               <div class="form-group">
                   <label class="text-info" for="id_first_name">First name:</label><br>
                   <input class="form-control" type="text" name="first_name" maxlength="100"  id="id_first_name" required>
               </div>
               <div class="form-group">
                   <label class="text-info" for="id_last_name">Last name:</label><br>
                   <input class="form-control" type="text" name="last_name" maxlength="100"  id="id_last_name" required>
               </div>
               <div class="form-group">
                   <label class="text-info" for="id_password1">Password:</label><br>
                   <input class="form-control" type="password" name="password1" id="id_password1" required>
               </div>
                <div class="form-group">
                   <label class="text-info" for="id_password2">Password Confirmation:</label><br>
                   <input class="form-control" type="password" name="password2" id="id_password2" required>
               </div>
               <div class="text-right">
                   <p class="text-info">Already have an account?<a class="text-info" href="/account/login/">Login</a></p><br>
               </div>
               <div class="from-group">
                   <input type="submit" class="btn btn-info btn-md" value="Submit">
               </div>
           </form>
       </div>
   </div>
{% endblock %}